version: "3.9"
services: 
  app:
    build: .
    ports:
      - 8080:80
    environment:
      - ConnectionStrings__Mongo=mongodb://mongo:27017
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017